"""Build full academic-style PDF reports for the two trained Ashique portions."""
from pathlib import Path
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak, KeepTogether

BASE=Path(__file__).resolve().parent
BLUE=colors.HexColor("#1f4e79"); LIGHT=colors.HexColor("#d9eaf7"); GREY=colors.HexColor("#f0f2f4")
styles=getSampleStyleSheet()
styles.add(ParagraphStyle("CoverTitle",parent=styles["Title"],fontName="Helvetica-Bold",fontSize=25,leading=31,textColor=BLUE,alignment=TA_CENTER,spaceAfter=18))
styles.add(ParagraphStyle("CoverSub",parent=styles["Normal"],fontSize=13,leading=18,alignment=TA_CENTER,textColor=colors.HexColor("#3f3f3f")))
styles.add(ParagraphStyle("H1x",parent=styles["Heading1"],fontSize=17,leading=21,textColor=BLUE,spaceBefore=4,spaceAfter=10))
styles.add(ParagraphStyle("H2x",parent=styles["Heading2"],fontSize=12,leading=15,textColor=BLUE,spaceBefore=7,spaceAfter=6))
styles.add(ParagraphStyle("BodyJ",parent=styles["BodyText"],fontSize=9.2,leading=13.2,alignment=TA_JUSTIFY,spaceAfter=7))
styles.add(ParagraphStyle("Small",parent=styles["BodyText"],fontSize=7.4,leading=9.4,alignment=TA_JUSTIFY))
styles.add(ParagraphStyle("Caption",parent=styles["BodyText"],fontSize=7.5,leading=9.5,alignment=TA_CENTER,textColor=colors.HexColor("#555555"),spaceAfter=7))
styles.add(ParagraphStyle("Callout",parent=styles["BodyText"],fontSize=9.2,leading=13,borderColor=BLUE,borderWidth=1,borderPadding=8,backColor=colors.HexColor("#edf5fb"),spaceBefore=5,spaceAfter=8))

def footer(canvas,doc):
    canvas.saveState(); canvas.setFont("Helvetica",7); canvas.setFillColor(colors.grey)
    canvas.drawCentredString(A4[0]/2,18,f"Padma Bridge ML Project | Page {doc.page}"); canvas.restoreState()

def table(data,widths=None,font=7.2,repeat=1):
    data=[[Paragraph(str(x),styles["Small"]) for x in row] for row in data]
    t=Table(data,colWidths=widths,repeatRows=repeat,hAlign="CENTER")
    t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),BLUE),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,GREY]),("GRID",(0,0),(-1,-1),.35,colors.HexColor("#9aa7b2")),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LEFTPADDING",(0,0),(-1,-1),4),("RIGHTPADDING",(0,0),(-1,-1),4),("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4)]));return t

def p(txt,style="BodyJ"): return Paragraph(txt,styles[style])
def bullets(items): return [Paragraph("• "+x,styles["BodyJ"]) for x in items]
def fig(path,caption,w=6.8*inch,h=3.5*inch): return [Image(str(path),width=w,height=h),p(caption,"Caption")]
def cover(title,subtitle,portion):
    return [Spacer(1,.45*inch),p("FINAL PROJECT REPORT","CoverSub"),Spacer(1,.25*inch),p(title,"CoverTitle"),p(subtitle,"CoverSub"),Spacer(1,.45*inch),p("CSE 4112: Machine Learning Laboratory<br/>Group B2 | Batch 2021<br/>Department of Computer Science and Engineering<br/>Khulna University of Engineering & Technology","CoverSub"),Spacer(1,.55*inch),table([["Submitted by","Submitted to"],["2107095 Sadia Mostafa<br/>2107096 Asique Ehetasamul Haque<br/>2107107 Md. Tahmid Islam<br/>2107109 Shormi Ghosh<br/>2107118 Adit Mugdha Das<br/>2107120 Siyam Khan","Dr. Muhammad Aminul Haque Akhand<br/>Professor<br/><br/>Nabil Faiyaz Sadi<br/>Lecturer"]],[3.2*inch,3.2*inch],8),Spacer(1,.45*inch),p(f"September 2026<br/>{portion}","CoverSub"),PageBreak()]

def doc(path): return SimpleDocTemplate(str(path),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=38,bottomMargin=32,title=path.stem,author="CSE 4112 Group B2")

def make_directional_figs(root,direct,best):
    f=root/"outputs"/"figures";f.mkdir(exist_ok=True,parents=True)
    q=direct[(direct.strategy=="Direct") & (~direct.model.str.contains("Persistence|Seasonal"))].copy(); q["display_mae"]=np.where(q.target.str.contains("cash"),q.MAE/1e6,q.MAE)
    fig,axs=plt.subplots(2,2,figsize=(10,7));
    for ax,(target,g) in zip(axs.ravel(),q.groupby("target")):
        g=g.sort_values("display_mae");ax.barh(g.model,g.display_mae,color="#4472c4");ax.set_title(target.replace("_"," ").title());ax.set_xlabel("MAE (million BDT)" if "cash" in target else "MAE (vehicles)")
    fig.tight_layout();fig.savefig(f/"model_mae_comparison.png",dpi=180,bbox_inches="tight");plt.close(fig)
    s=direct[direct.strategy=="Total-and-share"].groupby(["target","model"],as_index=False).MAE.mean(); s["display_mae"]=np.where(s.target.str.contains("cash"),s.MAE/1e6,s.MAE)
    fig,axs=plt.subplots(1,2,figsize=(10,4));
    for ax,kind in zip(axs,["traffic","cash"]):
        a=q[q.target.str.contains(kind)].groupby("model").display_mae.mean();b=s[s.target.str.contains(kind)].groupby("model").display_mae.mean();z=pd.concat([a.rename("Direct"),b.rename("Total-and-share")],axis=1).sort_values("Direct");z.plot.bar(ax=ax,color=["#4472c4","#70ad47"]);ax.set_title(kind.title()+" strategy comparison");ax.set_ylabel("Mean side MAE"+(" (million BDT)" if kind=="cash" else " (vehicles)"));ax.tick_params(axis="x",rotation=35)
    fig.tight_layout();fig.savefig(f/"strategy_comparison.png",dpi=180,bbox_inches="tight");plt.close(fig)
    return f

def directional_report():
    r=BASE/"directional_forecasting_ashique";out=r/"outputs";m=pd.read_csv(out/"directional_test_metrics.csv");best=pd.read_csv(out/"best_directional_models.csv");summ=json.loads((out/"run_summary.json").read_text());ev=pd.read_csv(out/"eid_direction_profile.csv");f=make_directional_figs(r,m,best)
    story=cover("Directional Traffic and Toll Revenue Forecasting for the Padma Bridge","Mawa- and Jajira-side forecasting, reconciliation and Eid direction analysis","Ashique portion: directional forecasting update")
    story += [p("Executive summary","H1x"),p(f"This extension converts the bridge-wide forecasting system into a side-specific system for Mawa traffic, Jajira traffic, Mawa toll revenue and Jajira toll revenue. The cleaned daily source produced <b>{summ['rows_modelled']:,}</b> complete modeling rows and <b>{summ['features']}</b> shifted, leakage-safe predictors. Persistence, seasonal persistence, Linear Regression, Random Forest, XGBoost, CatBoost and a residual MLP were evaluated chronologically."),p("XGBoost achieved the lowest direct test MAE for all four targets. Its MAPE was 8.88% for Mawa traffic, 8.85% for Jajira traffic, 8.34% for Mawa cash and 9.53% for Jajira cash. The total-and-share approach was also trained to guarantee arithmetic consistency when paired with a total forecast."),p("Main finding","H2x"),p("Recent side history and nonlinear boosting provide useful direction-level forecasts. Total-and-share forecasting is operationally attractive because its two side outputs sum exactly to the supplied total, but its deployment accuracy depends on the quality of the separate total forecast."),p("Work completed","H2x")]+bullets(["Created side-specific lags, rolling means, rolling standard deviations, shares, directional differences and revenue-per-vehicle history.","Trained 30 saved estimators across direct and total-and-share strategies.","Evaluated on the final 224 days without random splitting.","Produced model comparisons, date-level predictions and an Eid-relative side profile."])+[PageBreak()]
    story += [p("1. Introduction","H1x"),p("The original system forecasts only bridge-wide total traffic and total toll revenue. Operational planning also benefits from knowing how demand is distributed between the Mawa and Jajira toll-plaza sides. Directional forecasts can support staffing, lane allocation and event-day traffic management, particularly when travel patterns reverse before and after Eid."),p("1.1 Objectives","H2x")]+bullets(["Predict Mawa and Jajira traffic separately.","Predict Mawa and Jajira cash collection separately.","Compare direct target models with total-and-share allocation models.","Quantify side shares and ensure reconciled results sum to a bridge-wide total.","Describe directional patterns around Eid without claiming unverified northbound/southbound labels."])+[p("1.2 Scope","H2x"),p("The trained implementation is a one-day-ahead directional backtest using target-day calendar/weather information and bridge history ending at least one day earlier. The supplied brief also proposes 7- and 30-day directional forecasting; that joint extension requires the multi-horizon origin construction developed in the companion report and future weather assumptions."),PageBreak()]
    story += [p("2. Dataset and audit","H1x"),table([["Item","Value"],["Source","Padma daily traffic, toll, calendar and weather CSV"],["Raw coverage","26 Jun 2022 – 24 Aug 2026"],["Complete modeled rows",f"{summ['rows_modelled']:,}"],["Predictors",str(summ["features"])],["Test period",f"{summ['split']['test_start']} – {summ['split']['test_end']}"],["Test observations",str(summ['split']['test_rows'])]],[2.1*inch,4.4*inch]),p("2.1 Targets and consistency","H2x"),p("The four published side fields were cleaned from Indian comma grouping and retained as targets. Published totals were not replaced by sums of side values because the source contains a small number of inconsistencies. Direct forecasts may therefore have a non-zero reconciliation difference. In the total-and-share strategy, the predicted Mawa share is clipped to [0,1], the Jajira share is one minus the Mawa share, and allocation is made from the bridge total."),p("2.2 Leakage prevention","H2x"),p("Every traffic, cash, share, difference and revenue-per-vehicle feature was shifted by at least one day. Rolling windows begin from the previous day. Same-day side observations never appear among predictors. Calendar, Eid and expected-weather values are the only target-date inputs."),PageBreak()]
    story += [p("3. Feature engineering and experimental design","H1x"),table([["Feature family","Examples"],["Calendar","Cyclic weekday, month and day-of-year; weekend; railway indicator"],["Events","Holiday, Eid, distance to Eid and signed Eid-relative day"],["Weather","Mean/max/min temperature, rainfall, humidity and wind speed"],["Side history","Lags 1, 2, 3, 7, 14 and 28; rolling mean and standard deviation"],["Directional structure","Mawa/Jajira share, directional difference and side revenue per vehicle"],["Bridge totals","Shifted total traffic and total cash histories"]],[1.55*inch,4.95*inch]),p("3.1 Chronological evaluation","H2x"),p("Rows were ordered by date. The first 85% were used for model development and fitting and the final 15% were retained as the test period. This creates a realistic future evaluation and prevents later observations from influencing earlier predictions."),p("3.2 Models","H2x"),table([["Model","Purpose"],["Persistence / Seasonal","Last-day and last-week reference forecasts"],["Linear Regression","Interpretable linear baseline"],["Random Forest","Bagged nonlinear trees"],["XGBoost","Regularized gradient-boosted trees"],["CatBoost","Ordered boosting comparison for event/calendar interactions"],["Residual MLP","Neural model predicting change from the previous side value/share"]],[1.6*inch,4.9*inch]),PageBreak()]
    story += [p("4. Direct directional results","H1x"),p("The table reports the best non-baseline direct model for each target. Cash values are in BDT. MAE is the primary selection measure; RMSE emphasizes large misses, MAPE gives a scale-free percentage and R-squared measures explained test variation."),table([["Target","Best model","MAE","RMSE","MAPE","R-squared"]]+[[x.target,x.model,f"{x.MAE:,.0f}",f"{x.RMSE:,.0f}",f"{x.MAPE:.2f}%",f"{x.R2:.3f}"] for _,x in best.iterrows()],[1.15*inch,1.0*inch,1.0*inch,1.0*inch,.75*inch,.75*inch]),p("Interpretation","H2x"),p("XGBoost won all four direct targets on MAE. Traffic errors averaged roughly 700–750 vehicles per side, while cash errors averaged BDT 0.73–0.75 million per side. R-squared values from 0.732 to 0.801 indicate that the models explain a substantial share of daily test-period variation. The stronger Mawa traffic R-squared suggests somewhat more predictable variability on that side during this test window.")]+fig(f/"model_mae_comparison.png","Figure 1. Test MAE comparison across trained direct model families. Cash panels use million BDT; traffic panels use vehicles.",6.8*inch,4.65*inch)+[PageBreak()]
    direct=m[m.strategy=="Direct"].copy(); direct["Target"]=direct.target.str.replace("_"," ").str.title(); story += [p("5. Complete direct-model comparison","H1x"),table([["Target","Model","MAE","RMSE","MAPE","R²"]]+[[x.Target,x.model,f"{x.MAE:,.0f}",f"{x.RMSE:,.0f}",f"{x.MAPE:.2f}%",f"{x.R2:.3f}"] for _,x in direct.sort_values(["Target","MAE"]).iterrows()],[1.05*inch,1.05*inch,1.0*inch,1.0*inch,.7*inch,.6*inch],6.4),p("The persistence and seasonal baselines establish whether the machine-learning models add value beyond copying recent side values. Results differ by metric: for example, a residual model can have competitive percentage error while a boosted model better controls absolute error. Model choice should therefore consider both everyday MAE and high-demand RMSE, not a single accuracy percentage."),PageBreak()]
    story += [p("6. Direct versus total-and-share strategy","H1x"),p("Direct models predict each side independently. Total-and-share models predict only the Mawa fraction; the Jajira fraction is its complement. This guarantees zero reconciliation error once the shares are multiplied by a common total forecast."),table([["Criterion","Direct","Total-and-share"],["Side output","Four independent targets","Total × predicted share"],["Arithmetic consistency","Not guaranteed","Guaranteed"],["Dependency","Side model only","Share model plus total forecast"],["Interpretability","Individual levels","Demand level separated from allocation"],["Recommended use","Performance benchmark","Operational reconciled output"]],[1.3*inch,2.55*inch,2.55*inch])]+fig(f/"strategy_comparison.png","Figure 2. Average Mawa/Jajira MAE by strategy and model. Total-and-share values isolate allocation quality using the published total.",6.8*inch,2.75*inch)+[p("Important evaluation note","H2x"),p("The total-and-share backtest used the published test-day total to isolate share-allocation accuracy. It is therefore an oracle-total comparison, not a complete deployable forecast. In production, the total must come from the separately trained total traffic/toll model, and its error will propagate into both sides."),PageBreak()]
    peak=ev.loc[ev.mawa_traffic.add(ev.jajira_traffic).idxmax()]; story += [p("7. Eid and holiday directional analysis","H1x"),p(f"The signed Eid-relative profile groups observations from 14 days before through 14 days after Eid. The largest combined mean in this window occurred at relative day {int(peak.eid_relative_day):+d}. This profile helps identify when a surge begins, whether Mawa or Jajira is dominant and when the side share returns toward its ordinary level.")]+fig(f/"eid_direction_profile.png","Figure 3. Mean Mawa and Jajira traffic by signed day relative to Eid. These are descriptive associations across the available Eid events.",6.8*inch,3.65*inch)+[p("The number of Eid events is small, so each relative-day mean is sensitive to individual years. The side labels should not be translated to northbound or southbound until Bangladesh Bridge Authority definitions confirm that interpretation."),PageBreak()]
    story += [p("8. Actual-versus-predicted behavior","H1x"),p("The date-level plot compares each target with its selected direct prediction throughout the test period. Close tracking on routine dates supports operational usefulness; the widest gaps cluster around abrupt event-related changes, which are difficult to learn from only four years of history.")]+fig(f/"best_actual_vs_predicted.png","Figure 4. Actual side traffic/cash and the corresponding best direct model prediction during the held-out test period.",6.8*inch,4.35*inch)+[PageBreak()]
    story += [p("9. Limitations and responsible interpretation","H1x")]+bullets(["Only about four years of daily data and a small number of Eid events are available.","Published side and total values occasionally disagree; the audit preserves rather than hides that issue.","Observed historical weather is used for backtesting. Live use requires genuine forecast weather.","Mawa and Jajira are safely described as toll-plaza sides, not confirmed travel directions.","Unexpected closures, strikes, accidents and toll-rate changes are absent.","Feature importance and event profiles are predictive/descriptive, not causal."])+[p("10. Conclusion","H1x"),p("A complete directional forecasting extension was trained without altering the original project. XGBoost was the strongest direct model for every side target in the held-out test period. Total-and-share modeling provides exact reconciliation and a clear operational interpretation, provided that it is combined with an independently forecast bridge total. The main future priority is joint multi-horizon directional training with verified future calendars/weather and event-specific uncertainty intervals."),p("Appendix A. Delivered artifacts","H1x"),p("The project folder contains 30 serialized estimators, complete direct/share metric tables, date-level direct predictions, an Eid profile, figures, a machine-readable run summary and the reproducible training program."),p("Appendix B. Reproduction","H1x"),p("From the directional project folder, run: <font name='Courier'>python train_directional.py</font>. The script rebuilds features, fits all models and refreshes the outputs."),p("References","H1x"),p("1. Bangladesh Bridge Authority, Padma Bridge traffic and toll records, https://bba.gov.bd/<br/>2. Open-Meteo historical weather documentation, https://open-meteo.com/en/docs/historical-weather-api<br/>3. CSE 4112 Group B2 directional forecasting brief, September 2026.","Small")]
    doc(r/"directional_model_training_results.pdf").build(story,onFirstPage=footer,onLaterPages=footer)

def make_multi_figs(r,m,pred,best):
    f=r/"outputs"/"figures";f.mkdir(parents=True,exist_ok=True)
    q=m[(m.horizon_band=="all") & (~m.model.str.contains("Persistence|Seasonal"))].copy();q["v"]=np.where(q.target.eq("toll"),q.MAE/1e6,q.MAE)
    fig,axs=plt.subplots(1,2,figsize=(10,4));
    for ax,(target,g) in zip(axs,q.groupby("target")):
        g=g.sort_values("v");ax.bar(g.model,g.v,color="#4472c4");ax.tick_params(axis="x",rotation=30);ax.set_title(target.title()+" overall MAE");ax.set_ylabel("million BDT" if target=="toll" else "vehicles")
    fig.tight_layout();fig.savefig(f/"overall_model_comparison.png",dpi=180,bbox_inches="tight");plt.close(fig)
    fig,axs=plt.subplots(3,2,figsize=(11,9));
    for i,h in enumerate([1,7,30]):
      q=pred[pred.horizon==h].sort_values("target_date")
      for j,target in enumerate(["traffic","toll"]):
        name=best.loc[best.target==target,"model"].iloc[0];ax=axs[i,j];ax.plot(pd.to_datetime(q.target_date),q[target+"_actual"] if target+"_actual" in q else np.nan,label="Actual");ax.plot(pd.to_datetime(q.target_date),q[target+"_"+name],label=name,lw=1);ax.set_title(f"{target.title()} — horizon {h}");ax.legend(fontsize=7)
    fig.tight_layout();fig.savefig(f/"predictions_by_horizon.png",dpi=180,bbox_inches="tight");plt.close(fig)
    return f

def multihorizon_report():
    r=BASE/"multihorizon_forecasting_ashique";out=r/"outputs";m=pd.read_csv(out/"multihorizon_test_metrics.csv");best=pd.read_csv(out/"best_models.csv");pred=pd.read_csv(out/"multihorizon_test_predictions.csv");agg=pd.read_csv(out/"aggregate_period_metrics.csv");summ=json.loads((out/"run_summary.json").read_text())
    # Add actual columns from the underlying expanded dataset by joining source target dates.
    raw=pd.read_csv(BASE/"padma_bridge_ml_complete"/"data"/"raw"/"padma_toll_report_with_holidays_weather.csv");raw["target_date"]=pd.to_datetime(raw.Date,dayfirst=True).dt.strftime("%Y-%m-%d");raw["traffic_actual"]=pd.to_numeric(raw.Total_Traffic.astype(str).str.replace(",",""),errors="coerce");raw["toll_actual"]=pd.to_numeric(raw.Total_Cash.astype(str).str.replace(",",""),errors="coerce");pred=pred.merge(raw[["target_date","traffic_actual","toll_actual"]],on="target_date",how="left");f=make_multi_figs(r,m,pred,best)
    story=cover("Multi-Horizon Traffic and Toll Revenue Forecasting for the Padma Bridge","Next-day, weekly and monthly forecasting with horizon-aware models","Ashique portion: multi-horizon forecasting update")
    story += [p("Executive summary","H1x"),p(f"This project extends one-day Padma Bridge forecasting to a global direct system covering horizons 1–30. Historical origin dates were expanded into <b>{summ['expanded_samples']:,}</b> origin–horizon examples with <b>{summ['features']}</b> predictors. All samples from one origin remained in the same chronological partition, and no observed bridge value after the origin was used."),p("Across the complete held-out horizon set, XGBoost was the best traffic model with MAE 2,415 vehicles and MAPE 14.21%. CatBoost was the best toll model with MAE BDT 2.580 million and MAPE 14.16%. Performance declines with horizon, confirming the increased uncertainty of longer-range prediction."),p("Main finding","H2x"),p("A single horizon-aware model can learn next-day, weekly and monthly relationships while preserving origin-date integrity. Tree boosting is more reliable than persistence at longer horizons, although rare Eid periods remain substantially harder."),p("Work completed","H2x")]+bullets(["Generated horizon-labelled targets from 1 to 30 days.","Created origin-safe traffic/toll history and target-date calendar, event and weather inputs.","Trained and saved Random Forest, XGBoost, CatBoost and Residual MLP models for both targets.","Calculated horizon-band, holiday, Eid, weekly-total and 30-day-total metrics."])+[PageBreak()]
    story += [p("1. Introduction","H1x"),p("A one-day forecast supports immediate operations, but staffing, maintenance, revenue planning and event preparation require a longer view. Simply applying a one-day model repeatedly would introduce unknown future lags and compound errors. The implemented global-direct approach instead gives every training sample an explicit forecast horizon and predicts each future date directly from a common forecast origin."),p("1.1 Objectives","H2x")]+bullets(["Preserve next-day performance as a baseline.","Produce daily total traffic and toll predictions for horizons 1–30.","Compare ensemble and neural models consistently across horizons.","Measure daily, weekly-total, monthly-total, holiday and Eid errors.","Document future-weather uncertainty and avoid origin leakage."])+[p("1.2 Forecasting relationship","H2x"),p("History available on origin date t + target-date calendar/weather + horizon h → bridge total on date t+h."),PageBreak()]
    story += [p("2. Data construction","H1x"),table([["Item","Value"],["Raw Padma rows","1,520 daily records"],["Expanded complete samples",f"{summ['expanded_samples']:,}"],["Forecast horizons","1 through 30 days"],["Predictors",str(summ["features"])],["Test origins",str(summ['origin_split']['test_origins'])],["Test-origin range",f"{summ['origin_split']['test_start']} – {summ['origin_split']['test_end']}"]],[2.0*inch,4.5*inch]),p("2.1 Origin expansion","H2x"),p("For every eligible origin date, 30 supervised examples were created. The predictors describe the same origin history but each row receives a different horizon and target date. Traffic and toll targets are shifted backward by h days so that they refer to the correct future observation."),p("2.2 Target-date information","H2x"),p("Weekday, month, day-of-year, weekend, holiday, Eid proximity and rail-operation status are known from the target date. Historical target-date weather is used in the backtest to represent supplied forecast weather. For actual 8–30 day deployment, unavailable weather should be replaced with a genuine forecast or seasonal climatology and accompanied by a larger uncertainty statement."),PageBreak()]
    story += [p("3. Leakage prevention and chronological split","H1x"),p("Every example is assigned to train/development or test according to its forecast-origin date, not its target date. Thus, the 30 rows originating on one date cannot be split across partitions. Observed bridge-history columns stop at the origin date; later traffic and toll values are targets only."),p("This grouping rule is essential. Splitting expanded rows randomly would allow nearly identical samples from one origin to appear in both training and test data, producing an unrealistically optimistic score."),p("3.1 Features","H2x"),table([["Family","Variables"],["Origin history","Traffic/toll lags 0–28 and rolling mean/standard deviation"],["Target calendar","Cyclic weekday, month and annual encodings; weekend"],["Events","Public holiday, Eid and distance to nearest Eid"],["External","Target weather and railway-operation indicator"],["Horizon","Integer forecast_horizon from 1 to 30"]],[1.55*inch,4.95*inch]),p("3.2 Models","H2x"),table([["Model","Role"],["Persistence","Latest observed level for all future dates"],["Seasonal baseline","Most recent known value matching target weekday"],["Random Forest","Nonlinear bagged trees"],["XGBoost","Regularized gradient boosting"],["CatBoost","Alternative boosting model"],["Residual MLP","Predicts change relative to the origin value"]],[1.55*inch,4.95*inch]),PageBreak()]
    story += [p("4. Overall forecasting results","H1x"),table([["Target","Best model","MAE","RMSE","MAPE","R-squared"]]+[[x.target.title(),x.model,f"{x.MAE:,.0f}",f"{x.RMSE:,.0f}",f"{x.MAPE:.2f}%",f"{x.R2:.3f}"] for _,x in best.iterrows()],[1.0*inch,1.1*inch,1.0*inch,1.0*inch,.75*inch,.75*inch]),p("Interpretation","H2x"),p("XGBoost explains about half of the variation in 1–30 day traffic targets and provides the lowest traffic MAE. CatBoost provides the lowest toll MAE, while overall toll R-squared is lower at 0.314. This is expected because toll revenue combines traffic variation with changes in vehicle composition and revenue per vehicle, neither of which is directly forecast at long horizons.")]+fig(f/"overall_model_comparison.png","Figure 1. Overall held-out MAE across the four trained model families.",6.8*inch,2.8*inch)+[PageBreak()]
    story += [p("5. Accuracy by forecast horizon","H1x"),p("The horizon bands separate immediate prediction (day 1), short-range planning (days 2–7) and longer-range planning (days 8–30). Errors increase because recent observations become less informative and future events/weather are less certain.")]+fig(f/"error_by_horizon.png","Figure 2. Traffic and toll MAPE by horizon band for every trained model.",6.8*inch,2.85*inch)
    bands=m[(~m.model.str.contains("Persistence|Seasonal")) & m.horizon_band.isin(["1 day","2-7 days","8-30 days"])]
    story += [table([["Target","Band","Best model","MAE","MAPE","R²"]]+[[t,b,g.sort_values("MAE").iloc[0].model,f"{g.sort_values('MAE').iloc[0].MAE:,.0f}",f"{g.sort_values('MAE').iloc[0].MAPE:.2f}%",f"{g.sort_values('MAE').iloc[0].R2:.3f}"] for (t,b),g in bands.groupby(["target","horizon_band"])],[.8*inch,1.0*inch,1.05*inch,1.05*inch,.75*inch,.7*inch]),PageBreak()]
    story += [p("6. Daily prediction comparisons","H1x"),p("The plots below show representative test predictions at horizons 1, 7 and 30 for the selected overall model. Day-one estimates respond most closely to recent bridge conditions. At horizon 30, predictions are smoother and extreme peaks are harder to reproduce because the origin contains no intervening observed traffic.")]+fig(f/"predictions_by_horizon.png","Figure 3. Actual and selected-model forecasts at horizons 1, 7 and 30.",6.8*inch,5.55*inch)+[PageBreak()]
    story += [p("7. Weekly and 30-day aggregate performance","H1x"),p("Daily predictions were summed within each forecast origin and compared with the corresponding observed 7-day or 30-day total. Aggregation can cancel some positive and negative daily errors, but systematic bias remains visible."),table([["Target","Model","Period","Aggregate MAE","MAPE","R²"]]+[[x.target,x.model,f"{int(x.period_days)} days",f"{x.MAE:,.0f}",f"{x.MAPE:.2f}%",f"{x.R2:.3f}"] for _,x in agg.sort_values(["target","period_days","MAE"]).iterrows()],[.75*inch,1.05*inch,.75*inch,1.2*inch,.75*inch,.65*inch],6.8),p("Weekly totals are suited to staff and lane planning, while 30-day totals can support budgeting. They should not be interpreted as 30 independent one-day forecasts: all predictions in a row share the same origin information."),PageBreak()]
    ev=m[m.horizon_band.isin(["holiday","Eid +/-7d"])].sort_values(["target","horizon_band","MAE"]);story += [p("8. Holiday and Eid performance","H1x"),table([["Target","Segment","Model","N","MAE","MAPE","R²"]]+[[x.target,x.horizon_band,x.model,str(int(x.N)),f"{x.MAE:,.0f}",f"{x.MAPE:.2f}%",f"{x.R2:.3f}"] for _,x in ev.iterrows()],[.65*inch,.85*inch,1.0*inch,.55*inch,1.0*inch,.7*inch,.55*inch],6.2),p("Eid errors are much higher than overall errors. The test set contains relatively few distinct Eid events even though each event creates many origin–horizon rows. Those rows are correlated and should not be mistaken for thousands of independent festivals. Event-specific modeling and uncertainty intervals are therefore important next steps."),PageBreak()]
    story += [p("9. Prediction uncertainty and operational use","H1x"),p("The current deliverable produces point predictions. Longer horizons require wider uncertainty bands because weather, traffic composition and unexpected disruptions are not fully known. A future version should add quantile boosting or split-conformal intervals evaluated separately by horizon."),table([["Mode","Recommended interpretation"],["Next day","Operational traffic/toll estimate using fresh origin history"],["Next 7 days","Daily schedule plus weekly total; use forecast weather"],["Next 30 days","Planning scenario; substitute climatology where weather is unavailable"],["Eid period","High-uncertainty scenario requiring event monitoring"]],[1.25*inch,5.25*inch]),p("10. Limitations","H1x")]+bullets(["Approximately four years of history limit the number of repeated annual events.","Historical observed weather is more accurate than real long-range weather forecasts.","Future Jamuna observations are intentionally excluded after the origin.","Accidents, closures, strikes and toll policy changes are not modeled.","The compact local training configurations are reproducible but not an exhaustive hyperparameter search.","Point forecasts do not yet include calibrated prediction intervals."])+[PageBreak()]
    story += [p("11. Conclusion","H1x"),p("The multi-horizon extension successfully trains a single horizon-aware forecasting system for daily traffic and toll revenue from one to thirty days ahead. XGBoost is the strongest overall traffic model and CatBoost is the strongest overall toll model on test MAE. The results demonstrate useful planning ability while quantifying the expected loss of accuracy as the horizon grows. The most important deployment requirements are origin-safe feature updates, realistic future-weather inputs and explicit uncertainty for Eid and 30-day forecasts."),p("Appendix A. Delivered artifacts","H1x"),p("Eight serialized models, 6,255 row-level test predictions, 72 horizon/event metric rows, weekly and monthly aggregate tables, figures, a run summary and the complete training script are included."),p("Appendix B. Reproduction","H1x"),p("From the multi-horizon project folder, run: <font name='Courier'>python train_multihorizon.py</font>. It regenerates the expanded samples, saved models, tables and figures."),p("References","H1x"),p("1. Bangladesh Bridge Authority, Padma Bridge traffic and toll records, https://bba.gov.bd/<br/>2. Open-Meteo historical weather documentation, https://open-meteo.com/en/docs/historical-weather-api<br/>3. CSE 4112 Group B2 multi-horizon forecasting brief, September 2026.","Small")]
    doc(r/"multihorizon_model_training_results.pdf").build(story,onFirstPage=footer,onLaterPages=footer)

if __name__=="__main__":
    directional_report();multihorizon_report();print("Detailed reports generated.")
